#!/bin/sh
# -*- mode: shell-script; coding: utf-8-unix; -*-
#
# tangle files with org-mode
#
DIR=`pwd`
FILES=""


tangle_file () {
    emacs -Q --batch --eval "(progn (require 'org)(org-babel-load-file \"$*\"))"
}

# wrap each argument in the code required to call tangle on it
for i in "$@"; do
    tangle_file $i
done
